### ISSUE TITLE
QTree feature requests summary

### ISSUE THREAD

**Issue by pdanpdan** [quasarframework/quasar#6959]
Extract and make public functions to:
- [ ] get node parents - https://github.com/quasarframework/quasar/issues/5642
- [ ] get node children - https://github.com/quasarframework/quasar/issues/5642
- [ ] toggle node and children - https://github.com/quasarframework/quasar/issues/7052
- [ ] unload lazy loaded nodes - https://github.com/quasarframework/quasar/issues/6950
- [ ] expand all parents of node - https://github.com/quasarframework/quasar/issues/6894
- [ ] autoload expanded lazy nodes - https://github.com/quasarframework/quasar/issues/4751

Customize node styles/classes
- [ ] https://github.com/quasarframework/quasar/issues/1827
- [ ] https://github.com/quasarframework/quasar/issues/6493

Customize node props
- [x] https://github.com/quasarframework/quasar/issues/6661 (PR https://github.com/quasarframework/quasar/pull/7056)

NOFIX
- [ ] ~Add `no-nodes` slot - https://github.com/quasarframework/quasar/issues/6683~
- [ ] ~Empty header should not take space - https://github.com/quasarframework/quasar/issues/4889~

**Comment by qyloxe** [comment]
I call elephant in the room :-)
Please, please add drag'n'drop support to QTree...

**Comment by stgunholy** [comment]
> I call elephant in the room :-)
> Please, please add drag'n'drop support to QTree...

I submitted PR for this looong time ago, was not noticed, so I am just keeping my own q-tree fork in my codebase. there is not so much core there really

**Comment by JokerMartini** [comment]
any updates on this?

**Comment by othalan** [comment]
These enhancements would greatly benefit my use cases for QTree (in particular #6493).
Are updates coming?

**Comment by JokerMartini** [comment]
I'm wondering the same. i haven't seen any updates on the treeview stuff in quite some time.

**Comment by fyeeme** [comment]
Hote add drag'n'drop support to QTree...

**Comment by Carpediem94** [comment]
Hi, I'm not sure this is the right place for this question, but is relevant to a problem with QTree.

I there a way to make QTree always expanded, without arrow in the headers and headers not interactive (but not disabled)? Moreover when I add new nodes dynamically I want they are added expanded.
I try to make all nodes `expandable: false` and add `default-expand-all` to tree but all the nodes are closed when I create the tree.

Now I do an horrible workaround where I set the parent  `expandable: true`, then I call `treeRef.value.expandAll()` and at the end I reset parent to `expandable: false`. Moreover I hidden the arrow using CSS.
I apply this workaround when I initialize the tree or when I add new node with children.

Is there already a "legal" way to achieve this? Or could be a useful feature for other people?

**Comment by melicheradam** [comment]
Why the Qtree.setTicked() does not respect the tick strategy? This is really bad design since if I want to "synchronize" this filter with other elements, I have to reimplement the clicking strategy from scratch, if that is even possible. 

Actually 4th point of this issue 

Is there expected any movement on this one?

**Comment by shomalikhashayar** [comment]
Why I can't see a slot for no nodes available?

**Comment by Steeve55** [comment]
> Why the Qtree.setTicked() does not respect the tick strategy? This is really bad design since if I want to "synchronize" this filter with other elements, I have to reimplement the clicking strategy from scratch, if that is even possible.
> 
> Actually 4th point of this issue
> 
> Is there expected any movement on this one?

I m stuck at work because of this "bug". Is that possible to fix it ?
I want to make labels of the node tickable also.

And why this ticket has been closed ? https://github.com/quasarframework/quasar/issues/7052
It's an issue clearly.. At least add a new boolean argument in the method "setTicked" like "takeStrategyIntoAccount" with by default "false" to avoid a breaking change.

**Comment by xnextx** [comment]
> > Why the Qtree.setTicked() does not respect the tick strategy? This is really bad design since if I want to "synchronize" this filter with other elements, I have to reimplement the clicking strategy from scratch, if that is even possible.
> > Actually 4th point of this issue
> > Is there expected any movement on this one?
> 
> I m stuck at work because of this "bug". Is that possible to fix it ? I want to make labels of the node tickable also.
> 
> And why this ticket has been closed ? #7052 It's an issue clearly.. At least add a new boolean argument in the method "setTicked" like "takeStrategyIntoAccount" with by default "false" to avoid a breaking change.

I have exactly the same huge problem. I thought it was already solved, but still no. As far as I can see, I guess it's impossible to create a custom strategy (without rebuild quasar) that also allows you to select (and write to a variable) the parents after selecting the child.

**Comment by shomalikhashayar** [comment]
Why does q-timeline-entry have no slot for an avatar? I want to add my own elements to it.
